algorithm: softmatch
save_dir: ./saved_models
save_name: softmatch_svhn_250_2
resume: True
load_path: ./saved_models/softmatch_svhn_250_2/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 1024
num_train_iter: 1048576
num_eval_iter: 5000
num_labels: 250
batch_size: 64
eval_batch_size: 256
hard_label: True
T: 1.0
ulb_loss_ratio: 1.0
uratio: 7
dist_align: True
ema_p: 0.999
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
net: WideResNet
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data
dataset: svhn
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
seed: 2
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10009
dist_backend: nccl
gpu: None
